export const comunasRM: string[] = [
  "Santiago",
  "Providencia",
  "Ñuñoa",
  "Las Condes",
  "Vitacura",
  "Lo Barnechea",
  "La Reina",
  "Peñalolén",
  "Macul",
  "San Joaquín",
  "San Miguel",
  "Independencia",
  "Recoleta",
  "Quinta Normal",
  "Estación Central",
  "Cerrillos",
  "Cerro Navia",
  "Pudahuel",
  "Lo Prado",
  "Renca",
  "Conchalí",
  "Huechuraba",
  "Quilicura",
  "Maipú",
  "Puente Alto",
  "La Florida",
  "La Granja",
  "La Cisterna",
  "San Ramón",
  "El Bosque",
  "Lo Espejo",
  "Pedro Aguirre Cerda",
  "San Bernardo",
  "Buin",
  "Paine",
  "Calera de Tango",
  "Lampa",
  "Colina",
  "Tiltil",
  "Talagante",
  "Peñaflor",
  "Isla de Maipo",
  "El Monte",
  "Padre Hurtado",
  "Melipilla",
  "María Pinto",
  "Curacaví",
  "Alhué",
  "San Pedro",
];


